package com.tank.kai.greedao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BOOK".
 */
public class Book {

    private Long id;
    private Integer bid;
    private String name;
    private String author;
    private String img_url;
    private Integer chapter_count;
    private Integer status;

    public Book() {
    }

    public Book(Long id) {
        this.id = id;
    }

    public Book(Long id, Integer bid, String name, String author, String img_url, Integer chapter_count, Integer status) {
        this.id = id;
        this.bid = bid;
        this.name = name;
        this.author = author;
        this.img_url = img_url;
        this.chapter_count = chapter_count;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getBid() {
        return bid;
    }

    public void setBid(Integer bid) {
        this.bid = bid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getImg_url() {
        return img_url;
    }

    public void setImg_url(String img_url) {
        this.img_url = img_url;
    }

    public Integer getChapter_count() {
        return chapter_count;
    }

    public void setChapter_count(Integer chapter_count) {
        this.chapter_count = chapter_count;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

}
